// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

let version = "2.1.2"
let packageLibraryName = "ParticleEffects"

// Products define the executables and libraries a package produces, making them visible to other packages.
var products = [
	Product.library(
		name: "\(packageLibraryName) Library", // has to be named different from the iOSApplication or Swift Playgrounds won't open correctly
		targets: [packageLibraryName]
	),
]

#if !canImport(AppleProductTypes) && !os(Android) && !os(WASI)
products.append(.executable(name: "ParticleEffectsTerminalDemo", targets: ["ParticleEffectsTerminalDemo"]))
#endif

// Targets are the basic building blocks of a package, defining a module or a test suite.
// Targets can depend on other targets in this package and products from dependencies.
var targets = [
	Target.target(
		name: packageLibraryName,
		dependencies: [
			.product(name: "Compatibility Library", package: "compatibility"), // apparently needs to be lowercase.  Also note this is "Compatibility Library" not "Compatibility"
		],
		path: "Sources"
		// If resources need to be included in the module, include here
//		,resources: [ // unfortuantely cannot be conditionally compiled based on Swift version since the tool seems to be run on latest version.
//			Resource.process("Resources"),
//		]
//		,swiftSettings: [
//			.enableUpcomingFeature("BareSlashRegexLiterals")
//		]
	),
]

var platforms: [SupportedPlatform] = [ // SwiftUI's initial platform releases; the model itself is more portable.
	.macOS("10.15"),
	.tvOS("13"),
	.watchOS("6"),
]

#if canImport(PlaygroundSupport)
platforms += [
	.iOS("15.2"), // minimum for Swift Playgrounds support (maximum version for test iPhone 7)
]
#else
platforms += [
	.iOS("13"), // minimum release for Combine and SwiftUI
]
#endif

#if compiler(>=5.9) && os(visionOS)
platforms += [
	.visionOS("1.0"), // unavailable in Swift Playgrounds so has to be separate
]
#endif

#if canImport(AppleProductTypes) // swift package dump-package fails because of this
import AppleProductTypes

let executableTargetName = "\(packageLibraryName)TestAppModule"

products += [
	.iOSApplication(
		name: "\(packageLibraryName) App", // needs to match package name to open properly in Swift Playgrounds <v4.5, but must be different to run in v4.6 and greater.
		targets: [executableTargetName],
//		bundleIdentifier: "com.kudit.compatibility", // ignored in playgrounds
		teamIdentifier: "3QPV894C33",
		displayVersion: version,
		bundleVersion: "1",
		appIcon: .asset("AppIcon"),
		accentColor: .presetColor(.yellow),
		supportedDeviceFamilies: [
			.pad,
			.phone
		],
		supportedInterfaceOrientations: [
			.portrait,
			.landscapeRight,
			.landscapeLeft,
			.portraitUpsideDown(.when(deviceFamilies: [.pad]))
		],
//		capabilities: [
//			.outgoingNetworkConnections() // for networking tests
//		],
		appCategory: .developerTools
	),
]

targets += [
	.executableTarget(
		name: executableTargetName,
		dependencies: [
			.init(stringLiteral: packageLibraryName), // have to use init since normally would be assignable by string literal but we're not using a string literal
		],
		path: "Development"
		// The macOS-only SwiftPM tests live below Development for consistency with Compatibility, but they must
		// not also compile as application sources when Xcode evaluates this app target.
		,exclude: ["Resources", "ParticleEffectsTests"]
		// Include test app resources.
		,resources: [
//            .process("PlaygroundsAssets.xcassets")
		]
//		,swiftSettings: [
//			.enableUpcomingFeature("BareSlashRegexLiterals")
//		]
	),
//	.testTarget(
//		name: "\(packageLibraryName)Tests",
//		dependencies: [
//			.init(stringLiteral: packageLibraryName), // have to use init since normally would be assignable by string literal but we're not using a string literal
//		],
//		path: "Tests"
//	),
]

#endif // for Swift Package compiling for https://swiftpackageindex.com/add-a-package

#if !canImport(AppleProductTypes) && !os(Android) && !os(WASI)
targets.append(.executableTarget(
	name: "ParticleEffectsTerminalDemo",
	dependencies: [.init(stringLiteral: packageLibraryName)],
	path: "TerminalDemo"
))
#endif

// MARK: - Package tests
// Keep the test target out of Swift Playgrounds because its app-package manifest only supports the existing
// iOS application target. Standard SwiftPM and Xcode package loading on macOS still discover and run it.
#if !SwiftPlaygrounds && !canImport(PlaygroundSupport)
targets += [
	.testTarget(
		name: "\(packageLibraryName)Tests",
		dependencies: [
			.init(stringLiteral: packageLibraryName), // Preserve the computed target name used throughout this manifest.
			.product(name: "Compatibility Testing Library", package: "compatibility"),
		],
		path: "Development/ParticleEffectsTests"
	),
]
#endif

let package = Package(
	name: packageLibraryName,
	platforms: platforms,
	products: products,
	// include dependencies
	dependencies: [
		// Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/kudit/Compatibility.git", from: "1.19.9"),
	],
	targets: targets
)
